// Converts LaTeX math notation to readable plain symbols for students
export function stripLatex(text: string): string {
  return text
    .replace(/\$\$([^$]+)\$\$/g, '$1')
    .replace(/\$([^$\n]+)\$/g, '$1')
    .replace(/\\sqrt\{([^}]+)\}/g, '√$1')
    .replace(/\\sqrt\s+(\S+)/g, '√$1')
    .replace(/\\frac\{([^}]+)\}\{([^}]+)\}/g, '$1/$2')
    .replace(/\^{2}/g, '²').replace(/\^2(?!\d)/g, '²')
    .replace(/\^{3}/g, '³').replace(/\^3(?!\d)/g, '³')
    .replace(/\^{([^}]+)}/g, '^$1')
    .replace(/_{([0-9])}/g, (_, d) => '₀₁₂₃₄₅₆₇₈₉'[parseInt(d)])
    .replace(/_([0-9])/g,   (_, d) => '₀₁₂₃₄₅₆₇₈₉'[parseInt(d)])
    .replace(/\\cdot/g, '×')
    .replace(/\\times/g, '×')
    .replace(/\\div/g, '÷')
    .replace(/\\pm/g, '±')
    .replace(/\\mp/g, '∓')
    .replace(/\\geq/g, '≥').replace(/\\ge/g, '≥')
    .replace(/\\leq/g, '≤').replace(/\\le/g, '≤')
    .replace(/\\neq/g, '≠')
    .replace(/\\approx/g, '≈')
    .replace(/\\infty/g, '∞')
    .replace(/\\pi/g, 'π')
    .replace(/\\alpha/g, 'α').replace(/\\beta/g, 'β').replace(/\\gamma/g, 'γ')
    .replace(/\\delta/g, 'δ').replace(/\\Delta/g, 'Δ')
    .replace(/\\Rightarrow/g, '⇒').replace(/\\rightarrow/g, '→')
    .replace(/\\Leftrightarrow/g, '⟺').replace(/\\leftrightarrow/g, '↔')
    .replace(/\\left\(/g, '(').replace(/\\right\)/g, ')')
    .replace(/\\left\[/g, '[').replace(/\\right\]/g, ']')
    .replace(/\\left\|/g, '|').replace(/\\right\|/g, '|')
    .replace(/\\text\{([^}]+)\}/g, '$1')
    .replace(/\\[a-zA-Z]+\{([^}]*)\}/g, '$1')
    .replace(/\\[a-zA-Z]+\s*/g, '')
    .replace(/\{([^{}]+)\}/g, '$1')
    .replace(/[{}]/g, '')
}
